export default {
  submit: 'Submit',
  result: 'Result: ',
  back: 'Back',
  alert: 'Alert',
  error: 'Error',
  success: 'Success',
  ok : 'Ok',
  logout: 'logout',
  camera: 'Camera',
  elevator: 'Elevator',
  rotateImage: 'Rotate Image',
  instagram: 'Instagram',
  floorNumber: 'Floor number',
  elevatorNumber : 'Elevator number',
  simulator: 'Simulator',
  yourFloor : 'Your Floor',
  targetFloor: 'Target Floor',
  floor: 'Floor',
  direction: 'Direction',
  down : 'DOWN',
  up : 'UP',
  rotateImage: 'Rotate Image',
  userName: 'User name',
  password: 'Password',
  login : 'Login',
  unFollow: 'Unfollow',
  warning: 'Warning',
  youChooseTargetFloor: `You are in the elevator, let's choose your target floor.`,
  youChooseCurrentFloor: 'The first, you must choose your current floor.',
  instagram: 'Instagram'
}